// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwII8AZUWlxWggnfv6I1DXQ9RF_Wgdmfc',
    appId: '1:650051272658:web:b016d754d139a881c5120b',
    messagingSenderId: '650051272658',
    projectId: 'vidflix-movie-app',
    authDomain: 'vidflix-movie-app.firebaseapp.com',
    storageBucket: 'vidflix-movie-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7xvaSQdtIy3StxsW6WTrwwcb2rBmDwes',
    appId: '1:650051272658:android:2471648dfdc5d1cec5120b',
    messagingSenderId: '650051272658',
    projectId: 'vidflix-movie-app',
    storageBucket: 'vidflix-movie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYV3cU4iYc-GqCqnEiB-dxry9_e1Hz-lc',
    appId: '1:650051272658:ios:fb04bb6b3793cd27c5120b',
    messagingSenderId: '650051272658',
    projectId: 'vidflix-movie-app',
    storageBucket: 'vidflix-movie-app.appspot.com',
    iosClientId: '650051272658-k6f6iefqsoiqckdt0sgges6c1g7mqmvi.apps.googleusercontent.com',
    iosBundleId: 'com.davidcode0.vidflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYV3cU4iYc-GqCqnEiB-dxry9_e1Hz-lc',
    appId: '1:650051272658:ios:fb04bb6b3793cd27c5120b',
    messagingSenderId: '650051272658',
    projectId: 'vidflix-movie-app',
    storageBucket: 'vidflix-movie-app.appspot.com',
    iosClientId: '650051272658-k6f6iefqsoiqckdt0sgges6c1g7mqmvi.apps.googleusercontent.com',
    iosBundleId: 'com.davidcode0.vidflix',
  );
}
